Repository travel-calculator/root, pull requests merged in 2021-07, with the labels that each got.

#7 docs: add more detailed README
  README.md
  SETUP.md
  TECHNOLOGIES.md
  documentation/DOCUMENTATION.md
Labels: documentation

#30 feat(web.service): add ClientInfo schema (#28)
  .pnp.js
  .yarn/cache/@types-bson-npm-4.0.4-725db9127e-4b1f19b55e.zip
  .yarn/cache/@types-mongodb-npm-3.6.20-d771b4fe12-ee78b69d89.zip
  .yarn/cache/@types-node-npm-15.14.2-9671b0b90b-10982df2b5.zip
  .yarn/cache/bl-npm-2.2.1-f294e1ea12-438c510aa2.zip
  .yarn/cache/bluebird-npm-3.5.1-f0d1499f67-11347ec6d5.zip
  .yarn/cache/bson-npm-1.1.6-071be5c52e-d9e9e65dd4.zip
  .yarn/cache/debug-npm-3.1.0-9f0accb99b-1295acd5e0.zip
  .yarn/cache/denque-npm-1.5.0-fd3ca7b46a-3564778cda.zip
  .yarn/cache/kareem-npm-2.3.2-b3c6b60e2e-de7225607b.zip
  .yarn/cache/memory-pager-npm-1.5.0-46e20e6c81-6812af8165.zip
  .yarn/cache/mongodb-npm-3.6.8-6e13179694-45ae28f921.zip
  .yarn/cache/mongoose-legacy-pluralize-npm-1.0.2-2fbdda9a5a-a1f86450b3.zip
  .yarn/cache/mongoose-npm-5.13.2-e03369481f-1b1d6c13e8.zip
  .yarn/cache/mpath-npm-0.8.3-c764f5a56c-6c129da222.zip
  .yarn/cache/mquery-npm-3.2.5-4305c5382a-d7d611b3ee.zip
  .yarn/cache/optional-require-npm-1.0.3-2f124b03f7-be8556c35b.zip
  .yarn/cache/regexp-clone-npm-1.0.0-969a61b0d1-0cb16b8806.zip
  .yarn/cache/saslprep-npm-1.0.3-8db649c346-d007f50fe6.zip
  .yarn/cache/sift-npm-13.5.2-5c93d55c77-5c005114f8.zip
  .yarn/cache/sliced-npm-1.0.1-5537b02c49-af6bd9d911.zip
  .yarn/cache/sparse-bitfield-npm-3.0.3-cb80d0c89f-3d7ea483df.zip
  package.json
  packages/web.service/package.json
  packages/web.service/src/modules/client/index.ts
  packages/web.service/src/modules/client/schema.ts
  packages/web.service/src/modules/country/index.ts
  packages/web.service/src/modules/country/types.ts
  packages/web.service/src/modules/language/index.ts
  packages/web.service/src/modules/language/types.ts
  yarn.lock
Labels: backend, database

#45 feat(web.service): add post router for registration users (#21)
  .pnp.js
  .yarn/cache/@mapbox-node-pre-gyp-npm-1.0.5-4e17430ec9-82d337a6df.zip
  .yarn/cache/@types-bcrypt-npm-5.0.0-c074c165c2-4cf4cb6e13.zip
  .yarn/cache/bcrypt-npm-5.0.1-6815be1cfe-5a4f7e0eb1.zip
  .yarn/cache/detect-libc-npm-1.0.3-c30ac344d4-6cec442139.zip
  .yarn/cache/express-validator-npm-6.12.0-c925e57cd7-99ba3fb484.zip
  .yarn/cache/http-status-codes-npm-2.1.4-e5672be5a5-7cd5b1c88e.zip
  .yarn/cache/node-addon-api-npm-3.2.1-a29528f81d-b4c69283fc.zip
  .yarn/cache/passport-http-bearer-npm-1.0.1-482b7dfd57-a26f84c09c.zip
  .yarn/cache/passport-strategy-npm-1.0.0-5648a82a66-4ad0b62fcb.zip
  .yarn/cache/validator-npm-13.6.0-2ca88b50f3-6ae43bfd47.zip
  packages/web.service/.env
  packages/web.service/package.json
  packages/web.service/src/main.ts
  packages/web.service/src/modules/user/actions.ts
  packages/web.service/src/modules/user/index.ts
  packages/web.service/src/modules/user/router.ts
  packages/web.service/src/services/errorhandler.ts
  yarn.lock
Labels: backend

#47 feat(web.service): add changes to common app types (ComfortLevel, Per…
  packages/web.service/src/modules/comfortLevel/index.ts
  packages/web.service/src/modules/comfortLevel/level.ts
  packages/web.service/src/modules/hotel/schema.ts
  packages/web.service/src/modules/mealPrice/schema.ts
  packages/web.service/src/modules/person/index.ts
  packages/web.service/src/modules/person/schema.ts
  packages/web.service/src/modules/personType/index.ts
  packages/web.service/src/modules/personType/personType.ts
  packages/web.service/src/modules/personType/schema.ts
  packages/web.service/src/modules/personsNumber/index.ts
  packages/web.service/src/modules/personsNumber/personsNumber.ts
  packages/web.service/src/modules/season/index.ts
  packages/web.service/src/modules/season/season.ts
  packages/web.service/src/modules/transfer/schema.ts
  packages/web.service/src/modules/transferPersonQnt/schema.ts
  packages/web.service/src/modules/transferPrice/schema.ts
  packages/web.service/src/modules/transferTotal/schema.ts
  packages/web.service/src/modules/transportHourlyPersonQnt/schema.ts
  packages/web.service/src/modules/transportHourlyPrice/schema.ts
  packages/web.service/src/modules/transportHourlyTotalPrice/schema.ts
  packages/web.service/src/modules/type/index.ts
  packages/web.service/src/modules/type/schema.ts
  packages/web.service/src/modules/visit/schema.ts
  packages/web.service/src/modules/visitPrice/schema.ts
Labels: backend, database

#49 feat(web.service): add changes to Meal schemas (#27)
  packages/web.service/src/modules/meal/schema.ts
  packages/web.service/src/modules/mealPrice/schema.ts
Labels: backend, database

#48 feat(web.service): add router to show all users (#33)
  packages/web.service/src/modules/user/actions.ts
  packages/web.service/src/modules/user/router.ts
Labels: backend

#54 fix(web.service): fix validator at get /user
  packages/web.service/src/modules/user/router.ts
Labels: bug

#50 refactor(web.service): add changes to Transfer schemas (#22)
  packages/web.service/src/modules/transfer/schema.ts
  packages/web.service/src/modules/transferPersonQnt/schema.ts
  packages/web.service/src/modules/transferPrice/schema.ts
  packages/web.service/src/modules/transferTotal/index.ts
  packages/web.service/src/modules/transferTotal/schema.ts
  packages/web.service/src/modules/transferTransportTypeNumber/index.ts
  packages/web.service/src/modules/transferTransportTypeNumber/schema.ts
  packages/web.service/src/modules/transportType/index.ts
  packages/web.service/src/modules/transportType/transportTypes.ts
Labels: backend, database

#52 refactor(web.service): add MealTypeTime type and change Meal schemas (#27)
  packages/web.service/src/modules/meal/schema.ts
  packages/web.service/src/modules/mealPrice/schema.ts
  packages/web.service/src/modules/mealType/index.ts
  packages/web.service/src/modules/mealType/types.ts
Labels: backend, database

#53 refactor(web.service): add changes to Guide schema (#24)
  packages/web.service/src/modules/guide/schema.ts
Labels: backend, database

#56 refactor(web.service): add changes to Transport schema
  packages/web.service/src/modules/hourlyTransport/index.ts
  packages/web.service/src/modules/hourlyTransport/schema.ts
  packages/web.service/src/modules/transport/schema.ts
  packages/web.service/src/modules/transportHourlyPersonQnt/index.ts
  packages/web.service/src/modules/transportHourlyPersonQnt/schema.ts
  packages/web.service/src/modules/transportHourlyPrice/index.ts
  packages/web.service/src/modules/transportHourlyPrice/schema.ts
  packages/web.service/src/modules/transportHourlyTotalPrice/index.ts
  packages/web.service/src/modules/transportHourlyTotalPrice/schema.ts
Labels: backend, database

#57 refactor(web.service): add changes to Hotel schemas (#26)
  packages/web.service/src/modules/hotel/schema.ts
  packages/web.service/src/modules/hotelPrice/index.ts
  packages/web.service/src/modules/hotelPrice/schema.ts
  packages/web.service/src/modules/hotelRoom/schema.ts
Labels: backend, database

#58 fix(web.service): fix type of page and size at req.query
  packages/web.service/src/modules/user/router.ts
Labels: backend, bug

#59 feat(web.service): add cors to connect with front
  packages/web.service/package.json
  packages/web.service/src/main.ts
Labels: backend
